### ISSUE TITLE
IC with wrong designation.

### ISSUE THREAD

**Issue by Sven130889** [Proto-App/Proto-Android#200] opened 2023-02-07 18:19 UTC
The IC 7493 is incorrectly displayed as 7440.
![Screenshot_20230207_191702_P R O T O](https://user-images.githubusercontent.com/94050749/217331445-849ab601-4641-46c6-91f6-112b0beb51d7.jpg)

**Comment by Proto-App** [comment] 2023-02-07 18:52
@Sven130889 
Thank you for very fast report, could you give us steps to reproduce? We are not able to reproduce this issue:

![Screenshot_20230207_195149](https://user-images.githubusercontent.com/63373346/217338624-62abd363-6389-4037-8ea2-89dccd80477f.png)

**Comment by Proto-App** [comment] 2023-02-07 18:54
@Sven130889  Ok, now we get it, we will fix it immediately

**Comment by Proto-App** [comment] 2023-02-07 20:10
@Sven130889 
Fixed in v1.16.1 Should be available in next few hours.

**Closed as completed** 2023-02-19 09:20 UTC
Labels: bug, P1
