### ISSUE TITLE
Workspace import issue

### ISSUE THREAD

**Issue by borghim** [Proto-App/Proto-Android#329] opened 2024-03-03 08:42 UTC
Hi! I have problem importing my workspace from old device Samsung ZFlip3 to the new one which is Samsung ZFlip5. Same Android version 14 and same app version 1.27.0. 
Workspace export link is https://www.protosimulator.com/share?workspace=workspace_d0cbed77-2884-4d02-bed7-835e1050e425_1709454682582

When I open the app in the new device and click on this link I have an error reported in the image attached.
Thanks 
![Screenshot_20240303_093205_P R O T O](https://github.com/Proto-App/Proto-Android/assets/162011219/a6f17871-8935-44f1-b561-339e2e97bdcf)

**Comment by Proto-App** [comment] 2024-03-03 09:05
Hello @borghim 
On our device it works fine (there are 5 circuits).

Could you check "Supported web addresses" setting? You can find it in following steps (Samsung Galaxy Tab): 
Android settings -> Apps -> PROTO -> Set as default (Open supported links option should be turned on) -> Supported web addresses -> www.protosimulator.com should be turned on.

**Comment by borghim** [comment] 2024-03-03 09:15
Thanks for prompt reply!
Yes, 5 circuits..glad that it works for you.
The settings you are talking about I have changed already before otherwise the link was taken as a webpage. In my case the link opens the app but nothing is imported due to this unknown error..
![Screenshot_20240303_101038_Settings](https://github.com/Proto-App/Proto-Android/assets/162011219/3a2d4bd6-ba4a-45ca-a452-684822ecfbc8)
![Screenshot_20240303_101041_Settings](https://github.com/Proto-App/Proto-Android/assets/162011219/d14cdbb7-f057-452e-b7d5-a308a8ae7c82)

**Comment by Proto-App** [comment] 2024-03-03 09:21
Ok, very strange. Could you try to import one of your circuits: https://www.protosimulator.com/share?circuit=Passaggi_0_Trifase_1709457559391 ? If it won't work then we need to add more logs to PROTO to debug this issue.

**Comment by borghim** [comment] 2024-03-03 09:48
Unfortunately even one by one doesn't work for me. Two more info: 
1) I have succesfully imported the whole workspace on another phone but on this phone I don't own any addons and so I've missing parts.
2) I have tried to import the workspace on the old phone Zflip3, the phone used to generate the export link, but I have the same error.
I have uninstalled and installed back the app again but same thing..
Now, since the export link works and the problem seems to be only import, I will reset old phone to factory because I have sold it.
Thanks for your effort, I'm available for further test with the new phone.
Let me know, thanks

**Comment by Proto-App** [comment] 2024-03-03 09:52
Thank you for your feedback. Addons are not required to import/export. Can we prepare special version for you with more logs to debug this issue? It will be available for you via "Internal test track", we need some time to prepare it.

**Comment by borghim** [comment] 2024-03-03 09:59
Yes but without addons the circuit doesn't work of course on my other device where I didn't make the purchase
![17094598062826006187162234792142](https://github.com/Proto-App/Proto-Android/assets/162011219/f342302f-5140-4faa-99b1-e757ec6f11ed)

Anyway, yes I'm available..let me know when you are ready. If you don't have time no problem, I will make circuits again...that's not much work..
Thanks!

**Comment by Proto-App** [comment] 2024-03-03 10:16
Yes, you need addons if you have restricted components. All addons are tied to Google account (this is default behavior in Android). We would like to solve import issue because it is basic functionality and it should work :) We will prepare new version in next few days and will back to you.

**Comment by borghim** [comment] 2024-03-03 10:18
👍

**Comment by Jurgen2003** [comment] 2024-03-08 15:36
I also keep getting errors with importing

**Comment by Proto-App** [comment] 2024-03-08 20:49
Yes, we know. Tomorrow we will prepare test version. Of course you can participate with it :+1:

**Comment by Proto-App** [comment] 2024-03-09 10:19
@Jurgen2003 @borghim 
Could you share Gmail account for testing? We need them to give you access to new version.

**Comment by Jurgen2003** [comment] 2024-03-09 10:22
Dear @Proto-App  
My email is jurgenloosduinen@gmail.com
Thanks in advance

**Comment by Proto-App** [comment] 2024-03-09 10:24
Thanks, we will write you an email about further steps.

**Comment by Jurgen2003** [comment] 2024-03-09 10:49
Dear proto  
My email is jurgenloosduinen@gmail.com
Thanks in advance

**Comment by Jurgen2003** [comment] 2024-03-09 10:50
Dear@Proto-App 
![Screenshot_20240309_114941_Chrome.jpg](https://github.com/Proto-App/Proto-Android/assets/128260279/df4898d4-acd7-4f87-9be2-fa1750f9c85b)

What is this message
 I have another email to try  
Jurgenstorm@gmail.com

**Comment by borghim** [comment] 2024-03-09 11:31
@Proto-App 
my email is miborghi@gmail.com 
Thanks in advance

**Comment by Proto-App** [comment] 2024-03-09 13:39
@Jurgen2003 
Now it should be available for jurgenloosduinen@gmail.com

**Comment by Proto-App** [comment] 2024-03-09 16:45
@Jurgen2003 
Do you have device with Android 14?

**Comment by Jurgen2003** [comment] 2024-03-09 17:04
Yes i have. Andriod 14   6.0

**Comment by Proto-App** [comment] 2024-03-09 18:18
@Jurgen2003 @borghim 
Ok, probably this bug is connected with Android 14. On Monday we will provide fix in test version.

**Comment by Jurgen2003** [comment] 2024-03-09 18:39
@Proto-App 
Okay we'll see  
 If in the test version the problem is fixed it then via github. Report it ?

**Comment by Proto-App** [comment] 2024-03-09 19:50
@Jurgen2003 @borghim 
Fixed version should be available for you :wink: Please confirm that import is working as expected. We passed successful test on Android 14 emulator.

**Comment by Jurgen2003** [comment] 2024-03-10 06:42
Okay we'll see  
 If in the test version the problem is fixed it then via github. Report it ?

**Comment by Jurgen2003** [comment] 2024-03-10 06:43
@Proto-App 
The import problem in andriod 14 in with me. Resolved after updating to 1.27.1   
Greetings jurgen

**Comment by borghim** [comment] 2024-03-10 07:54
@Proto-App 
I confirm that also for me the issue has been solved since my workspace has been succesfully imported. Great job! 
Shall we uninstall test/debug version and install regular version from play store or not yet?
Thanks!

**Comment by Proto-App** [comment] 2024-03-10 10:19
@Jurgen2003 @borghim 
Great! We will release new version with fix on Monday in rollout mode. It should be available for everyone at the end of the week. You should uninstall test version and install official to receive future update.

**Comment by Proto-App** [comment] 2024-03-14 19:53
@Jurgen2003 @borghim 
Fixed in 1.28.0

**Comment by Jurgen2003** [comment] 2024-03-14 22:10
@Proto-App 
Thanks for fixing the problem version 1.28 installed and it works
Greets jurgen

**Closed as completed** 2024-03-15 06:22 UTC
Labels: bug, P1
